//************************************ B3D Framework - Copyright 2026 Marko Pintera **************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DPrerequisites.h"
#include "CoreObject/B3DRenderThread.h"
#include "Renderer/B3DPackedSlotAllocator.h"
#include "Utility/B3DModule.h"
#include "Allocators/B3DFrameAllocator.h"
#include "CoreObject/B3DCoreObject.h"

namespace b3d
{
	class RendererScene;
	namespace ecs { class Registry; }
	namespace render { class RendererScene; }

	/** @addtogroup Renderer-Internal
	 *  @{
	 */

	/**
	 * Helper used for batch synchronization of ECS objects from the main thread into packed arrays on the render thread.
	 *
	 * Stores a contiguous array of packets containing the data to synchronize, as well as render slots which determine to which
	 * entries in the packed renderer arrays those packets should be applied to.
	 *
	 * TODO: While in transition state the system is working with RenderProxy's, but will eventually operate purely on data.
	 *
	 * @tparam DataType		Data type that is being synced.
	 * @tparam ProxyType	Type of the render proxy (e.g. render::Renderable). TODO - Temporary
	 */
	template<typename DataType, typename ProxyType>
	struct TBatchSyncBuffer
	{
		using ProxyShared = SPtr<ProxyType>;

		u32 Count = 0;
		u32 Maximum = 0;
		DataType* Packets = nullptr;
		ProxyShared* Proxies = nullptr; // TODO - Temporary
		SlotId* RendererIds = nullptr;

		/** Allocate internal arrays for @p count entries using @p allocator. */
		void Allocate(FrameAllocator& allocator, u32 count)
		{
			Packets = reinterpret_cast<DataType*>(allocator.AllocateAligned(sizeof(DataType) * count, alignof(DataType)));
			Proxies = reinterpret_cast<ProxyShared*>(allocator.AllocateAligned(sizeof(ProxyShared) * count, alignof(ProxyShared)));
			RendererIds = reinterpret_cast<SlotId*>(allocator.AllocateAligned(sizeof(SlotId) * count, alignof(SlotId)));

			Maximum = count;
		}

		/** Construct a new PacketType in-place and store the associated proxy and renderer ID. Returns a reference to the constructed packet. */
		template<typename... Args>
		DataType& Add(const ProxyShared& proxy, SlotId rendererId, Args&&... args)
		{
			B3D_ASSERT(Count < Maximum);

			auto* packet = new(&Packets[Count]) DataType(std::forward<Args>(args)...);
			new(&Proxies[Count]) ProxyShared(proxy);
			RendererIds[Count] = rendererId;
			++Count;
			return *packet;
		}

		/**
		 * Iterates entries, calling @p fn(PacketType&, ProxyType&, SlotId rendererId) for each.
		 * Destructs the buffer data for this entry after the callback finishes.
		 */
		template<typename Fn>
		void Each(Fn&& fn)
		{
			for(u32 entryIndex = 0; entryIndex < Count; ++entryIndex)
			{
				fn(Packets[entryIndex], *Proxies[entryIndex], RendererIds[entryIndex]);
				Packets[entryIndex].~DataType();
				Proxies[entryIndex].~ProxyShared();
			}
		}

		/** Frees the frame-allocated Packets, Proxies, and RendererIds arrays. Must be called after Each(). */
		void Free(FrameAllocator& allocator)
		{
			if(Packets)
				allocator.Free((u8*)Packets);

			if(Proxies)
				allocator.Free((u8*)Proxies);

			if(RendererIds)
				allocator.Free((u8*)RendererIds);
		}
	};

	/**
	 * Interface used for batch synchronization of main thread objects with their renderer-side representations.
	 * Uses ECS for fast iteration. The intention is that the caller marks dirty objects with an ECS tag,
	 * which can then be used by this system to fetch all dirty objects and store the dirty data
	 * into a frame-allocated buffer to be passed to the render thread so it can be applied there.
	 */
	class IRendererObjectSyncHandler
	{
	public:
		virtual ~IRendererObjectSyncHandler() = default;

		/**
		 * Scans the provided registry for dirty objects, generates the update packets and stores them into a batch buffer allocated
		 * by @p allocator. Returns pointer to the batch buffer memory.
		 */
		virtual void* SyncRead(ecs::Registry& registry, FrameAllocator& allocator) = 0;

		/**
		 * Applies data from a batch buffer generated by SyncRead to objects on the render thread,
		 * and frees the frame-allocated batch data via @p allocator.
		 *
		 * @note Render thread only.
		 */
		virtual void SyncWrite(void* batchData, FrameAllocator& allocator) = 0;
	};

	/**
	 * Module that orchestrates ECS-based batch sync between main thread objects and their renderer-side representations.
	 * Different types can register their own sync handlers, which are then ran every frame before kicking off
	 * render thread work.
	 *
	 * Handler registration is global (type → factory). Handler instances are owned per-scene by RendererScene,
	 * and created via CreateHandlers() during RendererScene::Initialize().
	 */
	class B3D_EXPORT RendererSyncManager : public Module<RendererSyncManager>
	{
	public:
		using HandlerFactory = Function<UPtr<IRendererObjectSyncHandler>(RendererScene&)>;

		RendererSyncManager();
		~RendererSyncManager();

		/**
		 * Run the full sync pipeline: SyncRead on main thread, queue SyncWrite operation on the render thread.
		 * If @p swapBuffers is true, rotate the frame allocator ring buffer.
		 */
		void SyncToRenderThread(bool swapBuffers);

		/**
		 * @name Internal
		 * @{
		 */

		/** Registers a handler factory to be applied when the module starts up. Called from static initializers. */
		static void RegisterHandlerFactoryAtLoadTime(HandlerFactory factory);

		/** Creates handler instances for a scene from all registered factories. Called by RendererScene::Initialize(). */
		Vector<UPtr<IRendererObjectSyncHandler>> CreateHandlers(RendererScene& rendererScene);

		/** @} */
	private:
		struct HandlerFrameData
		{
			IRendererObjectSyncHandler* Handler;
			void* BatchData;
		};

		struct PerFrameSyncData
		{
			FrameAllocator* Allocator = nullptr;
			TInlineArray<HandlerFrameData, 8> HandlerData;
		};

		void SyncRead(FrameAllocator* allocator);
		void SyncWrite();

		Vector<HandlerFactory> mHandlerFactories;
		List<PerFrameSyncData> mPerFrameSyncData;
		Mutex mSyncDataMutex;
		FrameAllocator* mSyncAllocators[RenderThread::kSyncBufferCount + 1];
		u32 mActiveFrameAllocatorIndex = 0;
	};

	/** Ensures that TRendererObjectSyncHandler types are registered at application load time. */
	template<typename HandlerType>
	struct InitializeSyncHandlerOnLoadTime
	{
		InitializeSyncHandlerOnLoadTime()
		{
			RendererSyncManager::RegisterHandlerFactoryAtLoadTime([](RendererScene& scene) { return B3DMakeUnique<HandlerType>(scene); });
		}

		void MakeSureIAmInstantiated() {}
	};

	/**
	 * Helper base class that automatically registers itself with RendererSyncManager at application load time,
	 * and provides common slot management logic (allocator caching, command consume/replay).
	 *
	 * The derived class must implement two CRTP methods:
	 * - AllocatorT& GetAllocator(RendererScene& rendererScene) — returns the allocator for this type from the scene.
	 * - void ReplayCommands(render::RendererScene& scene, const SlotCommand* commands, u32 count) — calls the
	 *   appropriate replay virtual on the scene.
	 *
	 * @tparam SelfType				The concrete handler type deriving from this class.
	 * @tparam SlotAllocatorType	The packed slot allocator type for this object kind.
	 */
	template<typename SelfType, typename SlotAllocatorType>
	class TRendererObjectSyncHandler : public IRendererObjectSyncHandler
	{
	public:
		TRendererObjectSyncHandler(RendererScene& rendererScene)
			: mRendererScene(*B3DGetRenderProxy(&rendererScene))
		{
			sInitializeOnLoadTime.MakeSureIAmInstantiated();
			mAllocator = &static_cast<SelfType*>(this)->GetAllocator(rendererScene);
		}

	protected:
		/** Consumes commands from the allocator and frame-allocates a copy. */
		u32 ConsumeAndAllocateCommands(FrameAllocator& allocator, SlotCommand*& outCommands)
		{
			B3D_ASSERT(mAllocator != nullptr);
			const auto& commands = mAllocator->ConsumeCommands();
			u32 commandCount = (u32)commands.size();
			if(commandCount == 0)
			{
				outCommands = nullptr;
				return 0;
			}
			outCommands = reinterpret_cast<SlotCommand*>(allocator.AllocateAligned(sizeof(SlotCommand) * commandCount, alignof(SlotCommand)));
			memcpy(outCommands, commands.data(), sizeof(SlotCommand) * commandCount);
			return commandCount;
		}

		SlotAllocatorType* mAllocator = nullptr;
		render::RendererScene& mRendererScene;

	private:
		static InitializeSyncHandlerOnLoadTime<SelfType> sInitializeOnLoadTime;
	};

	template<typename SelfType, typename AllocatorT>
	InitializeSyncHandlerOnLoadTime<SelfType> TRendererObjectSyncHandler<SelfType, AllocatorT>::sInitializeOnLoadTime;

	/** @} */
} // namespace b3d
