//************************************ B3D Framework - Copyright 2026 Marko Pintera **************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DPrerequisites.h"
#include "CoreObject/B3DRenderThread.h"
#include "Utility/B3DModule.h"
#include "Allocators/B3DFrameAllocator.h"

namespace b3d
{
	namespace ecs { class Registry; }

	/** @addtogroup RenderProxy-Internal
	 *  @{
	 */

	/**
	 * Helper used for batch synchronization of core objects and their render proxies. Stores a contiguous array
	 * of packets containing the data to synchronize, as well as references to the render proxies to which those
	 * packets should be applied to.
	 *
	 * @tparam PacketType	Type of the sync packet (e.g. Renderable::FullSyncPacket).
	 * @tparam ProxyType	Type of the render proxy (e.g. render::Renderable).
	 */
	template<typename PacketType, typename ProxyType>
	struct TBatchSyncBuffer
	{
		using ProxyShared = SPtr<ProxyType>;

		u32 Count = 0;
		u32 Maximum = 0;
		PacketType* Packets = nullptr;
		ProxyShared* Proxies = nullptr;

		/** Allocate internal arrays for @p count entries using @p allocator. */
		void Allocate(FrameAllocator& allocator, u32 count)
		{
			Packets = reinterpret_cast<PacketType*>(allocator.AllocateAligned(sizeof(PacketType) * count, alignof(PacketType)));
			Proxies = reinterpret_cast<ProxyShared*>(allocator.AllocateAligned(sizeof(ProxyShared) * count, alignof(ProxyShared)));

			Maximum = count;
		}

		/** Construct a new PacketType in-place and store the associated proxy. Returns a reference to the constructed packet. */
		template<typename... Args>
		PacketType& Add(const ProxyShared& proxy, Args&&... args)
		{
			B3D_ASSERT(Count < Maximum);

			auto* packet = new(&Packets[Count]) PacketType(std::forward<Args>(args)...);
			new(&Proxies[Count]) ProxyShared(proxy);
			++Count;
			return *packet;
		}

		/**
		 * Iterates entries, calling @p fn(PacketType&, ProxyType&) for each.
		 * Destructs the buffer data for this entry after the callback finishes.
		 */
		template<typename Fn>
		void Each(Fn&& fn)
		{
			for(u32 entryIndex = 0; entryIndex < Count; ++entryIndex)
			{
				fn(Packets[entryIndex], *Proxies[entryIndex]);
				Packets[entryIndex].~PacketType();
				Proxies[entryIndex].~ProxyShared();
			}
		}

		/** Frees the frame-allocated Packets and Proxies arrays. Must be called after Each(). */
		void Free(FrameAllocator& allocator)
		{
			if(Packets)
				allocator.Free((u8*)Packets);

			if(Proxies)
				allocator.Free((u8*)Proxies);
		}
	};

	/**
	 * Interface used for batch synchronization of main thread objects with their render proxies.
	 * Uses ECS for fast iteration. The intention is that the caller marks dirty objects with an ECS tag,
	 * which can then be used by this system to fetch all dirty objects.
	 */
	class IRenderProxySyncHandler
	{
	public:
		virtual ~IRenderProxySyncHandler() = default;

		/**
		 * Scans the provided registry for dirty objects, generates the update packets and stores them into a batch buffer allocated
		 * by @p allocator. Returns pointer to the batch buffer memory.
		 */
		virtual void* SyncRead(ecs::Registry& registry, FrameAllocator& allocator) = 0;

		/**
		 * Applies data from a batch buffer generated by SyncRead to objects on the render thread,
		 * and frees the frame-allocated batch data via @p allocator.
		 *
		 * @note Render thread only.
		 */
		virtual void SyncWrite(void* batchData, FrameAllocator& allocator) = 0;
	};

	/**
	 * Module that orchestrates ECS-based batch sync between main thread objects and their render proxies.
	 * Different types can register their own sync handlers, which are then ran every frame before kicking off
	 * render thread work.
	 *
	 * Handler registration is global (type → factory), but handler instances are per-scene. When a new scene
	 * is created, all registered factories are invoked to produce per-scene handler instances. When syncing,
	 * all live scenes are iterated and each scene's handlers are called with that scene's registry.
	 */
	class B3D_EXPORT RenderProxySyncManager : public Module<RenderProxySyncManager>
	{
	public:
		using HandlerFactory = Function<UPtr<IRenderProxySyncHandler>()>;

		RenderProxySyncManager();
		~RenderProxySyncManager();

		/**
		 * Run the full sync pipeline: SyncRead on main thread, queue SyncWrite operation on the render thread.
		 * If @p swapBuffers is true, rotate the frame allocator ring buffer.
		 */
		void SyncToRenderThread(bool swapBuffers);

		/**
		 * @name Internal
		 * @{
		 */

		/** Registers a handler factory to be applied when the module starts up. Called from static initializers. */
		static void RegisterHandlerFactoryAtLoadTime(HandlerFactory factory);

		/** Notifies the system that a new scene was created. Creates per-scene handler instances from all registered factories. */
		void NotifySceneCreated(ecs::Registry* registry);

		/** Notifies the system that a scene is being destroyed. Removes per-scene handler instances. */
		void NotifySceneDestroyed(ecs::Registry* registry);

		/** @} */
	private:
		struct HandlerFrameData
		{
			IRenderProxySyncHandler* Handler;
			void* BatchData;
		};

		struct PerFrameSyncData
		{
			FrameAllocator* Allocator = nullptr;
			TInlineArray<HandlerFrameData, 8> HandlerData;
		};

		void SyncRead(FrameAllocator* allocator);
		void SyncWrite();

		Vector<HandlerFactory> mHandlerFactories;
		UnorderedMap<ecs::Registry*, Vector<UPtr<IRenderProxySyncHandler>>> mPerSceneHandlers;
		List<PerFrameSyncData> mPerFrameSyncData;
		Mutex mSyncDataMutex;
		FrameAllocator* mSyncAllocators[RenderThread::kSyncBufferCount + 1];
		u32 mActiveFrameAllocatorIndex = 0;
	};

	/** Ensures that TRenderProxySyncHandler types are registered on application load. */
	template<typename HandlerType>
	struct InitializeSyncHandlerOnLoadTime
	{
		InitializeSyncHandlerOnLoadTime()
		{
			RenderProxySyncManager::RegisterHandlerFactoryAtLoadTime([] { return B3DMakeUnique<HandlerType>(); });
		}

		void MakeSureIAmInstantiated() {}
	};

	/**
	 * Helper base class that automatically registers itself with RenderProxySyncManager at load time.
	 *
	 * @tparam SelfType The concrete handler type deriving from this class.
	 */
	template<typename SelfType>
	class TRenderProxySyncHandler : public IRenderProxySyncHandler
	{
	public:
		TRenderProxySyncHandler()
		{
			sInitializeOnLoadTime.MakeSureIAmInstantiated();
		}

	private:
		static InitializeSyncHandlerOnLoadTime<SelfType> sInitializeOnLoadTime;
	};

	template<typename SelfType>
	InitializeSyncHandlerOnLoadTime<SelfType> TRenderProxySyncHandler<SelfType>::sInitializeOnLoadTime;

	/** @} */
} // namespace b3d
