//************************************* B3D Framework - Copyright 2026 Marko Pintera *************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DSLPrerequisites.h"
#include "Material/B3DShaderCompiler.h"
#include "Material/B3DShaderReflection.h"

namespace b3d
{
	/** @addtogroup bsfSL
	 *  @{
	 */

	/** Describes how HLSL should be cross compiled to a particular low-level shading language. */
	struct HLSLCrossCompileTarget
	{
		const char* TargetLanguage = nullptr; /**< XShaderCompiler output target id (e.g. Xsc::TargetLanguage::VKSL450), or an optional backend's string id. */
		const char* PreprocessorDefine = nullptr; /**< Emitted into the HLSL input as "#define <X> 1" before compilation. nullptr for none. */

		/**
		 * True when the cross-compiled output keeps the per-stage entry function names of the HLSL input (vsmain,
		 * fsmain, ...), which HLSL-family output languages do. False when the output language requires a single fixed
		 * entry name and the cross compiler therefore renames the entry function to "main" (GLSL-family outputs).
		 * Determines the entry point recorded on - and used to compile bytecode from - the cross-compiled programs.
		 */
		bool KeepsEntryPointNames = false;
	};

	/** Generated source and its associated shader reflection. */
	struct ShaderCrossCompileOutput
	{
		ShaderCrossCompileOutput() = default;

		String Source; /**< Generated shader source; empty when the stage is absent. */
		TShared<ShaderReflection> Reflection; /**< Metadata using the generated entry-point names and bindings. */
	};

	/**	Transforms HLSL into other shading languages, and also outputs reflection data. */
	class HLSLCrossCompiler
	{
	public:
		/**
		 * Cross compiles the provided HLSL source code into the requested output language.
		 *
		 * @param	hlsl						HLSL to cross compile.
		 * @param	type						GPU program stage that the HLSL code represents.
		 * @param	target						Description of the language to cross-compile to.
		 * @param	inOutStartBindingSlot		First generated resource binding, updated past the assigned bindings. Use the same starting slot for every stage of a pass.
		 * @param	output						Generated source and reflection; empty source means the stage is absent.
		 * @param	sharedReflection			Optional reflection from another stage of the same pass. Reuses its parameters after checking the source layout matches.
		 * @return								A result object containing an error message if not successful.
		 */
		static ShaderCompilerResult CrossCompile(const String& hlsl, GpuProgramType type, const HLSLCrossCompileTarget& target, u32& inOutStartBindingSlot, ShaderCrossCompileOutput& output, const ShaderReflection* sharedReflection = nullptr);

		/**
		 * Registers every cross-compilation target supported by this build. Call once during plugin start-up.
		 * The implementation is generated by CMake.
		 */
		static void RegisterSupportedTargets();

		/**
		 * Unregisters the GPU bytecode compilers registered by RegisterSupportedTargets() from the shared
		 * ShaderCompilers module. The implementation is generated by CMake.
		 */
		static void UnregisterSupportedTargets();

		/**
		 * Looks up the cross-compilation target registered for the given shading language identifier.
		 *
		 * @param	language	Engine shading language identifier to look up.
		 * @return				Pointer to the registered target, or null if no target is registered for @p language.
		 */
		static const HLSLCrossCompileTarget* GetTarget(const String& language);

		/** Reflects material-visible parameters and discovers entry points. An optional target selects the binding layout and backend defines. */
		static ShaderCompilerResult Reflect(const String& hlsl, ShaderReflection& outReflection, const HLSLCrossCompileTarget* target = nullptr);

	private:
		/**
		 * Registers (or replaces) the cross-compilation target for the given shading language identifier.
		 *
		 * @param	language	Engine shading language identifier the target applies to (e.g. "vksl").
		 * @param	target		Description of how to cross-compile to that language.
		 */
		static void RegisterTarget(const String& language, const HLSLCrossCompileTarget& target);
	};

	/** @} */
} // namespace b3d
